name: Build Release Artifacts
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build x86
      run: msbuild /m /p:Platform=x86 /p:Configuration=Release al-khaser.sln

    - name: Build x64
      run: msbuild /m /p:Platform=x64 /p:Configuration=Release al-khaser.sln

    - name: Attach Binaries to release
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "al-khaser_x*.exe"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
